config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'business#index'
   resources :favorites

end

app/models/business.rb
class Business
  attr_reader :id, :name, :url, :review_count, :distance, :rating, :address

  def initialize api_data
    @id = api_data.fetch "id"
    @name = api_data.fetch "name"
    @url = api_data.fetch "url"
    @review_count = api_data.fetch "review_count"
    @distance = api_data.fetch "distance"
    @rating = api_data.fetch "rating"
    @address = api_data.fetch("location").fetch("address")
  end
end 

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
end

app/models/yelp_api.rb
class YelpApi
  API_HOST  = 'http://api.yelp.com/'
  TOKENS = {consumer_key: Figaro.env.yelp_consumer_key, consumer_secret: Figaro.env.yelp_consumer_secret, token: Figaro.env.yelp_token, token_secret: Figaro.env.yelp_token_secret
  }

  def self.restaurants_nearby loc, term
    lat,long = loc
    @connection = Faraday.new(API_HOST) do |conn|
      conn.request :oauth, TOKENS
      conn.adapter :net_http
    end
    
    s = @connection.get("v2/search?ll=#{lat},#{long}&limit=5&term=#{term}&sort=1")
    s = JSON.parse(s.body)
    bizzies = s["businesses"].map {|s| Business.new(s)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/business_controller.rb
class BusinessController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    category = "food"
    loc = [38.9014957,-77.0391753]
    @restaurants = YelpApi.restaurants_nearby loc, category
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end
  def create
    Favorite.create! user_id: current_user.id, name: params[:name], rating: params[:rating], review_count: params[:review_count], address: params[:address], url: params[:url]
    head :ok
  end
  def destroy
    current_user.favorites.find_by_id(params[:id]).delete
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/views/business/index.html.slim
table class="table table-striped table-hover"
  th Name
  th Rating
  th # of Reviews
  th Distance
  th Address
  th URL 
  -if current_user
    th Add to Favorites 
  - @restaurants.each do |r|
    tr 
      td class="name" = r.name 
      td class="rating" = r.rating 
      td class="review_count" = r.review_count 
      td class="distance" = r.distance 
      td class="address" = r.address.first 
      td class="url": a href="#{r.url}" Yelp Page 
      -if current_user  
        td
          button.btn-small Favorite

app/views/favorites/index.html.slim
table class="table table-striped table-hover"
  th Name
  th Rating
  th # of Reviews
  th Address
  th URL 
  -@favorites.each do |f|
    tr data-favorite-id="#{f.id}"
      td = f.name
      td = f.rating
      td = f.review_count
      td = f.address
      td: a href="#{f.url}" Yelp Page 
      td
        button.btn.delete Delete
  

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Nomster"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href=root_path Nomster
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
            ul.nav.navbar-nav.pull-right
              - if current_user
                li= link_to "Favorites" , favorites_path
                li= link_to current_user.email, ""
                li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                li= link_to "Sign In", new_user_session_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      footer
        p &copy; Company 2015